# Generated by Django 5.1.1 on 2024-09-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booksapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="publish_date",
            new_name="published_date",
        ),
    ]
